stages:
- test
- code-analysis

before_script:
  - export CI_PROJECT_NAME=`basename $CI_PROJECT_DIR`
  - export CI_PROJECT_GROUP=`dirname $CI_PROJECT_DIR | sed 's!.*/!!'`

# Roda testes unitários de python.
.unit-test: &unit-test
    script:
    - make init
    - make test

unit test:
    stage: test
    tags: [python-351]
    <<: *unit-test
    artifacts:
       paths:
       - reports
       expire_in: 10min

code convention:
    stage: code-analysis
    tags: [python-351]
    script:
    - make init
    - make code-convention

metrics:
    stage: code-analysis
    tags: [metrics]
    script:
    - understand-python-analyze
    - srccheck-python-analyze
    - s101-python-analyze
    artifacts:
      paths:
      - reports
      expire_in: 10min